# Generated by Django 5.2.7 on 2025-10-21 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email_verified"], name="userprof_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email_verification_token"], name="userprof_token_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["created_at"], name="userprof_created_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["email_verified", "-created_at"], name="userprof_ver_created_idx"
            ),
        ),
    ]
