# Generated by Django 5.0 on 2025-10-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_client_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe customer identifier associated with this tenant",
                max_length=255,
                null=True,
            ),
        ),
    ]
