# Generated by Django 5.2.7 on 2025-10-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_client_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
