# Generated by Django 5.2.7 on 2025-11-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="endpoint",
            name="monitors_endpoint_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="endpoint",
            name="monitors_endpoint_schedule_idx",
        ),
        migrations.RemoveIndex(
            model_name="endpoint",
            name="monitors_endpoint_tenant_url_idx",
        ),
    ]
